image:
  file: gitpod/.gitpod.dockerfile
ports:
  - port: 4000
    onOpen: open-preview 
tasks:
  - name: Phx
    init: gitpod/init.sh
    command: gitpod/start.sh
vscode:
  extensions:
    - elixir-lsp.elixir-ls
